### ISSUE TITLE
Powershell?

### ISSUE THREAD

**Issue by ChildishGiant** [dracula/powershell#1]
Thanks for the theme! Is there any way to apply this to powershell too?

**Comment by waf** [comment]
Hey, thanks for taking a look! In my very limited experimentation, the colors seem to work just fine in powershell. The `colortool` command will apply the Dracula colors correctly.

The custom prompt would need to be done differently though, maybe sitting on top of [posh-git](https://github.com/dahlbyk/posh-git/).

I'll play around with it in the next couple of days and see what can figure out.

**Comment by waf** [comment]
Hi @ChildishGiant, just pushed powershell support instructions in the readme. For the custom prompt, it uses posh-git so there aren't any conflicts between the two prompts.
