### ISSUE TITLE
Titlebar color

### ISSUE THREAD

**Issue by Fabio24Silva** [dracula/powershell#10]
![Capturar](https://user-images.githubusercontent.com/28763038/54070505-abe55700-4258-11e9-814f-88db9edd83dc.PNG)

Hi guys, thanks for this theme, on your screenshots your titlebar color changes too, but mine didn't change. How can I change it?

**Comment by waf** [comment]
Hi, thanks for raising the issue! I don't think Windows 10 has functionality to change the titlebar color per-application. So in this case you'll need to set it for all applications:

> Windows 10 Settings → Personalization → Colors → Custom color → More → #262835.

You're right that it's unclear, so I've added this note to the README. Thanks!

**Comment by Fabio24Silva** [comment]
It's working, thanks!
