### ISSUE TITLE
It doesn't work after upgrading to 19H1.

### ISSUE THREAD

**Issue by cnluzhang** [dracula/powershell#11]
I joined Release Insider Program. My system version is Version 1903 18362.53.
The color config is invalid after I upgrading from 1809 to 1903.

**Comment by waf** [comment]
Thanks for the report! I'll upgrade shortly and see what's going on.

**Comment by waf** [comment]
@cnluzhang I've just opened https://github.com/dracula/powershell/pull/13 which I think should fix the issue. Could you please try downloading the `ColorTool.zip` archive from that PR ([direct link here](https://github.com/dracula/powershell/blob/5ee930fb110a9cc1c4eda885719eea3751b34803/dist/ColorTool.zip))? 

After running `ColorTool.exe -b Dracula-ColorTool.itermcolors` from the above download, you'll probably need to clear out any subkeys under `HKEY_CURRENT_USER\Console\` (but don't delete the top level `Console` key):

<img src="https://user-images.githubusercontent.com/97195/56468822-b308a300-645b-11e9-8984-8a9f2b33a280.png" width=500px />

Then when you start a new console, the theme should work. If it works for you, I'll submit a patch upstream to the `ColorTool` project so we don't need to maintain a special version. Thanks!

**Comment by cnluzhang** [comment]
Sorry for my late reply.
It works on CMD, but the PowerShell shows like below.
![image](https://user-images.githubusercontent.com/8707726/56873443-edc69880-6a64-11e9-84f0-ff6ead559eb5.png)
The registry likes below.
![image](https://user-images.githubusercontent.com/8707726/56873468-1cdd0a00-6a65-11e9-9768-066b369f93b8.png)

**Comment by waf** [comment]
Thanks for your help with troubleshooting this, @cnluzhang! I can't quite see it in your screenshot, but do you have a value called `ScreenColors`, and it's set to `7` like this?

![image](https://user-images.githubusercontent.com/97195/57077112-68b5da80-6d15-11e9-9b10-908c185c328e.png)

If not, you can add it: 

1. Right Click -> New
2. Choose DWORD
3. Change the name to `ScreenColors`
4. Right click ScreenColors -> Modify
5. Change value to `7`
6. Close and open powershell

If that still doesn't work, I'd appreciate it if you export your registry values, Right click on "Console" -> Export and then send me the file.

Thanks!

**Comment by cnluzhang** [comment]
Hi waf, I have already had the value, here is my exported file.

[consolereg.txt](https://github.com/dracula/powershell/files/3153554/consolereg.txt)

**Comment by waf** [comment]
@cnluzhang thank you, that was very useful. I figured out the problem I think. Could you please download the latest version from the repository ([direct link to zip file](https://raw.githubusercontent.com/waf/dracula-cmd/master/dist/ColorTool.zip)) and run the `install.cmd` from inside the ColorTool directory?

I believe the shortcut files in the start menu are caching some parts of the old theme. The "install.cmd" will remove that cache, so it loads colors from the registry as expected.

**Comment by cnluzhang** [comment]
@waf The theme works well.
But I can't save the font configuration. Every time I apply the color theme and save the font, it goes back to Raster Fonts when I restart the powershell.

**Comment by waf** [comment]
@cnluzhang sorry for the slow response. When you change the font, are you changing it in the "Defaults" menu item or the "Properties" item?

<img src="https://user-images.githubusercontent.com/97195/60112145-804f9380-9799-11e9-8adc-e9a411221429.png" alt="image" style="max-width:100%;" width="300px">

I've found there's some inconsistent behavior here, if you're changing it in "Properties" try changing it in "Defaults" or vice-versa.

**Comment by waf** [comment]
@cnluzhang I'm going to resolve this issue, because the theme is working for 19H1. Feel free to open another issue if you're still having the raster font issue. Thanks!
