### ISSUE TITLE
Error loading ini file "./.\Dracula-ColorTool.itermcolors"     for key "DARK_BLACK"     the value "" is invalid

### ISSUE THREAD

**Issue by rakhtar92** [dracula/powershell#12]
![DraculaForPowershell](https://user-images.githubusercontent.com/20411595/56426711-de15ba00-62d6-11e9-92a7-c37f0dc91f45.PNG)

Hey guys, I tried using the colorTool to change the powershell theme as described. But it does not work. Please find the screenshot attached.

**Comment by waf** [comment]
Thanks for the report @rakhtar92. I think this error is not a real error (it comes from Microsoft's [ColorTool project](https://github.com/Microsoft/console/tree/master/tools/ColorTool)) and can be ignored. ColorTool supports both `ini` and `itermcolors` file formats, we used the `itermcolors` format, so any "ini file" errors can be ignored. I'll see if I can improve the error messages with a PR to that project.

For your theme, I think it correctly applied. Could you please verify your console's properties matches the following? (right click on your terminal's Titlebar -> Properties -> Colors -> Screen Background)

<img src="https://user-images.githubusercontent.com/97195/56468898-b2244100-645c-11e9-9736-3c7a14314780.png" width="400px" />

Thanks!

**Comment by waf** [comment]
I've fixed the error message in https://github.com/Microsoft/console/pull/418

**Comment by waf** [comment]
@rakhtar92 I'm closing out this issue, but we can reopen if you're still seeing a problem.
