### ISSUE TITLE
Colors not loading from profile configuration

### ISSUE THREAD

**Issue by azivkovi** [dracula/powershell#18]
![Annotation 2019-08-17 015813](https://user-images.githubusercontent.com/47382298/63203837-845daa80-c092-11e9-87be-3a3415dae668.png)

I followed the install instructions and this is the error I get. I tried -TokenType instead, but I get the same error for this parameter as well.

The Microsoft.PowerShell_profile.ps1 file contents are just the Dracula config, nothing else.

I will appreciate your help with this because I don't see what I'm doing wrong. Thank you.

**Comment by yunjianyang** [comment]
Same error here. Followed the instruction step by step.

**Comment by waf** [comment]
Thanks for reporting this. I'm away from my computer at the moment, but I'll look into this in the next day or two.

**Comment by waf** [comment]
@azivkovi could you post the output of `(Get-Module PSReadLine).Version` please?

**Comment by azivkovi** [comment]
@waf Here it is:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1
```

**Comment by azivkovi** [comment]
Quick update from me, it seems my installation of PSReadLine 2 beta failed, so I tried a different command : `install-module psreadline -requiredversion 2.0.0-beta2 -AllowPrerelease -Force -AllowClobber"` found here https://github.com/PowerShell/PowerShellGet/issues/318 .

This instealled the 2.0 version and now my version output is

```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0     -1
```

And the error is gone.

**Comment by yunjianyang** [comment]
> Quick update from me, it seems my installation of PSReadLine 2 beta failed, so I tried a different command : install-module psreadline -requiredversion 2.0.0-beta2 -AllowPrerelease -Force -AllowClobber" found here PowerShell/PowerShellGet#318 .
> This instealled the 2.0 version and now my version output is
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 2      0      0     -1
> 
> And the error is gone.

Worked.

**Comment by waf** [comment]
Thanks! I'll update the readme with your alternate install command.
