### ISSUE TITLE
Unable to change prompt

### ISSUE THREAD

**Issue by rmtracey** [dracula/powershell#19]
During my setup, I set my `prompt` environment variable to `$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m`, as specified in the setup instructions. I decided that I don't like the arrow, so I deleted the environment variable, but my prompt did not revert to the old style. I also tried fully uninstalling the theme through the uninstall script and reinstalling - that didn't work either. Now I've re-added the `prompt` environment variable with a different value, but my prompt still will not change - it seems to be stuck as the initial value I first set it to.

Any ideas on how to fix this?

**Comment by rmtracey** [comment]
Apologies, I didn't realize that this was coming from the provided posh-git settings, and that the `prompt` env var is only for cmd.exe.

**Comment by waf** [comment]
Thanks for raising the issue! I've updated the README to clear up the confusion.
