### ISSUE TITLE
Colortool.exe its not recognized

### ISSUE THREAD

**Issue by Censoretti** [dracula/powershell#23]
![image](https://user-images.githubusercontent.com/55342496/66258666-576a7180-e77e-11e9-80a8-bbbb4c382b6d.png)

i'm trying to install colortool.exe, but aways get this error, and dont know whats the wrong in ths, someone can help me?

**Comment by waf** [comment]
Hi @dagashy, sorry for the slow response. Can you please `cd` to the colortool directory?

For example:

```console
cd \users\rodri\desktop\colortool
install.cmd
```

**Comment by ghost** [comment]
> i'm trying to install colortool.exe, but aways get this error, and dont know whats the wrong in ths, someone can help me?

`colortool.exe` isn't to be installed on your machine, but executed by `install.cmd` batch file.

**Comment by waf** [comment]
@dagashy I'm closing this issue, please let me know if you're still seeing issues!
