### ISSUE TITLE
Wrong background color

### ISSUE THREAD

**Issue by ghost** [dracula/powershell#25]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

I am following _pari passu_ the instructions in README.md to install Dracula theme on PoSh. When I execute install.cmd, however, my terminal is abhorrently pink:

![Anotação 2019-12-01 072846](https://user-images.githubusercontent.com/53820433/69912818-692e6500-140d-11ea-8dee-1dddd61705f8.jpg)

Even when I open a new terminal, its background color is pink. When I go to Properties page and select the right black color tone, all works as expected.

I'm on Windows 10 v1909 running PowerShell 5.1 Build 18362 Rev. 145

**Comment by waf** [comment]
@joaosantana Hi, thanks for reporting the issue. 
Would you be able to export the following registery key and share it with me?

HKEY_CURRENT_USER\Console

This will list your current console configurations to a plain-text file, so I can see the the details of the issue. Thanks!

**Comment by ghost** [comment]
@waf Thank you for your quick response.

My HKCU/Console hive content:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"CtrlKeyShortcutsDisabled"=dword:00000000
"CursorColor"=dword:ffffffff
"CursorSize"=dword:00000019
"DefaultBackground"=dword:ffffffff
"DefaultForeground"=dword:ffffffff
"EnableColorSelection"=dword:00000000
"ExtendedEditKey"=dword:00000001
"ExtendedEditKeyCustom"=dword:00000000
"FaceName"="Consolas"
"FilterOnPaste"=dword:00000001
"FontFamily"=dword:00000036
"FontSize"=dword:000e0000
"FontWeight"=dword:00000190
"ForceV2"=dword:00000001
"FullScreen"=dword:00000001
"HistoryBufferSize"=dword:00000032
"HistoryNoDup"=dword:00000000
"InsertMode"=dword:00000001
"LineSelection"=dword:00000001
"LineWrap"=dword:00000001
"LoadConIme"=dword:00000001
"NumberOfHistoryBuffers"=dword:00000004
"PopupColors"=dword:000000f5
"QuickEdit"=dword:00000001
"ScreenBufferSize"=dword:23290078
"ScreenColors"=dword:00000007
"ScrollScale"=dword:00000001
"TerminalScrolling"=dword:00000000
"TrimLeadingZeros"=dword:00000000
"WindowAlpha"=dword:000000ff
"WindowSize"=dword:001e0078
"WordDelimiters"=dword:00000000
"ColorTable00"=dword:00352826
"ColorTable01"=dword:00f892bc
"ColorTable02"=dword:007bf94f
"ColorTable03"=dword:00a47261
"ColorTable04"=dword:005454ff
"ColorTable05"=dword:00c579ff
"ColorTable06"=dword:006cb7ff
"ColorTable07"=dword:00f1f7f7
"ColorTable08"=dword:00545454
"ColorTable09"=dword:00f892bc
"ColorTable10"=dword:007bf94f
"ColorTable11"=dword:00fce88a
"ColorTable12"=dword:005454ff
"ColorTable13"=dword:00c579ff
"ColorTable14"=dword:008bf9f0
"ColorTable15"=dword:00ffffff
"CurrentPage"=dword:00000001

[HKEY_CURRENT_USER\Console\Git Bash]
"FaceName"="Lucida Console"
"FontFamily"=dword:00000036
"FontSize"=dword:000e0000
"FontWeight"=dword:00000190

[HKEY_CURRENT_USER\Console\Git CMD (Deprecated)]
"FaceName"="Lucida Console"
"FontFamily"=dword:00000036
"FontSize"=dword:000e0000
"FontWeight"=dword:00000190
```

**Comment by ghost** [comment]
When i saw `DefaultBackground` value set tô `0xffffffff`, I was thinking that the issue was with my machine. So I've do a clean install and tested in other three machines, with the same pink background result.

After select the very first tone in Properties, however, an `uninstall.cmd` followed by a new `install.cmd` command works as expected.

**Comment by dianligegege** [comment]
> When i saw `DefaultBackground` value set tô `0xffffffff`, I was thinking that the issue was with my machine. So I've do a clean install and tested in other three machines, with the same pink background result.
> 
> After select the very first tone in Properties, however, an `uninstall.cmd` followed by a new `install.cmd` command works as expected.

hey man,Is your problem solved? i have met the same question.

**Comment by ghost** [comment]
@dianligegege Not yet, but if you go to Powershell's window Properties, Colors and select the very first color square to background color, will work.

**Comment by dianligegege** [comment]
@joaosantana  thanks so much ,that's works for me

**Comment by waf** [comment]
Just an update on this one, the [ColorTool.exe](https://github.com/microsoft/terminal/tree/master/src/tools/ColorTool) is supposed to set the background color in the registry. I'm currently trying to figure out why that's not happening.

**Comment by pjoe** [comment]
Ran into this as well.

FWIW: Here is the setting in the properties for matching the correct bg color:
![image](https://user-images.githubusercontent.com/1846572/74512816-65d55080-4f09-11ea-8719-9b194d4071f0.png)

**Comment by pjoe** [comment]
Hmm on further check other colors are also wrong, and pretty unreadable (git info):

![image](https://user-images.githubusercontent.com/1846572/74513030-e5631f80-4f09-11ea-996c-5dce186c2e3f.png)

**Comment by pjoe** [comment]
Okay think I got it working here. Steps I took:

1. Updated ColorTool.exe to latest version from https://github.com/microsoft/terminal/releases/tag/1904.29002

2. Manually copied the .lnk files over to my start menu. Before I was also using a link pinned to the taskbar - might also have been the issue.
