### ISSUE TITLE
CTRL + C stopped working? Am I the only one?

### ISSUE THREAD

**Issue by EnVy28** [dracula/powershell#28]
After applying this theme, ctrl + C stopped working while inside powershell and cmd.
I did everything in order from "Colors Installation -> PowerShell Prompt -> CMD.exe Prompt -> Windows Titlebar Color"...

No error encountered during installation...

When CMD or Powershell is opened, without typing anything CTRL + C works fine, but when running an console application, ctrl + c does not exit the app...

Tried on:
1. Windows Explorer -> Open Windows Powershell
2. Windows Explorer -> Open Windows Powershell as Admin
3. Windows button (right click) -> Windows Powershell
4. Windows button (right click) -> Windows Powershell as Admin
5. Windows Search -> Windows Powershell
6. Windows Search -> Windows Powershell as admin
7. Windows Search -> CMD
8. Windows Search -> CMD as admin
9. VSCode -> Intergrated Terminal (Powershell)
10. VSCode -> Intergrated Terminal (CMD)

In all cases, ctrl + c does not work

**Comment by waf** [comment]
Hi @EnVy28, thanks for reporting this. I haven't seen this before. You said that:

> but when running an console application, ctrl + c does not exit the app

Is there a specific app that's having this problem? I tried writing a little console app that calls `Console.ReadKey()` to accept user input, and <kbd>ctrl+c</kbd> exited the app (dropped me back on the prompt as expected).

**Comment by EnVy28** [comment]
Hi @waf 

There is no specific application, I don't think, but what I use regularly is "node" and some GO app I built personally.

Also, this only happens on my Laptop, when I tried  to install this on my home pc, everything works well with no problem at all.

Maybe I did something wrong?

Maybe try this:
On VSCode, I changed this [setting](https://mypublicbucketforsharinglul.s3-ap-northeast-1.amazonaws.com/Capture001.PNG) so that everytime I hit ctrl+shift+c, powershell would open up...

That where ctrl + c stops working, in that instance of powershell or cmd...

**Comment by seia-soto** [comment]
Me either Node.JS and Go installed on my laptop(I'll speak this laptop as computer or other things can be recognizable). However, there is nothing seems non-sense.

In other words, you should check another thing affecting key binding.

**Comment by waf** [comment]
Thanks @Seia-Soto. I'm thinking this must be related to PSReadline. I've seen some reports that ctrl-c was reworked as part of the PSReadline 2.0 release.

@EnVy28: Could you please try the following?

1. Update your PSReadline package: `update-module PSReadline -Force`, then close/reopen your terminal)
1. Try to reproduce the problem. If it's fixed, great, if not please continue:
1. Run this script to output your version of PSReadline and please post it here:
    ```powershell
    $v = (Get-Module PSReadline).Version
    $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
    if ($m) {
        $v = "$v-" + $m.Matches[0].Groups[1].Value
    }
    "PSReadline version: $v"
    ```
1. Please provide a bit more detail about which node / go commands are exhibiting the problem. I've tried reproducing it with `npm init` but was unable. VSCode was also OK for me.

Thanks! I really appreciate helping with this.

**Comment by waf** [comment]
Closing out some older issues. Feel free to re-open if it's still affecting you.
