### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by jargule** [dracula/powershell#29]
I got install issues, here are my steps
This worked
`PS C:\Users\Owner\ColorTool> ./install.cmd`

NuGet installed successfully
`PS C:\Windows\system32> Install-Module -Name NuGet`

But then 
`PS C:\Windows\system32> Install-Module -Name PowerShellGet -Force`
The error
`PackageManagement\Install-Package : The module PowerShellGet cannot be installed because the catalog signature in PowerShellGet.cat does not match the hash generated from the module.`
`At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21`
`$null = PackageManagement\Install-Package @PSBoundParameters`
`CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],`
   `Exception`
    `+ FullyQualifiedErrorId : InvalidCatalogSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage`

**Comment by waf** [comment]
Hi @jargule, are you still seeing this error? I think it may have been a temporary error with that module. I see other similar reports (for example, https://github.com/Azure/azure-powershell/issues/11656, https://github.com/PowerShell/PowerShellGallery/issues/96) in other powershell projects around the same timeframe.

**Comment by waf** [comment]
I'm closing this for now as it's not reproducible and I think there were some temporary problems with that `PowerShellGet` package a few weeks ago. If it's still happening for anyone, feel free to reopen.
