### ISSUE TITLE
Installguid for windows terminal?

### ISSUE THREAD

**Issue by Cmoen11** [dracula/powershell#30]
Hi, since windows terminal has been released.. Is there any install guide for this? :)

**Comment by waf** [comment]
Hi @Cmoen11, yep, there are a few!

- [Windows Terminal](https://github.com/dracula/windows-terminal) repo
- For a version that matches cmd/powershell in this repo, there's the [Windows 10 Terminal Dracula Theme](https://github.com/dracula/powershell/blob/master/theme/Windows%2010%20Terminal%20Dracula%20Theme.json).

**Comment by Cmoen11** [comment]
Thanks!!
