### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by arpitkaushal** [dracula/powershell#31]
Can someone please help me with uninstalling this? 
I ran `uninstall.cmd` but I cannot figure out how to exactly delete the environment variable profile in cmd. 

Please help.

**Comment by gawronix** [comment]
type $profile
copy path
vim "path"
delete all data in $profile
save
done :)

**Comment by arpitkaushal** [comment]
Hi @gawronix 
I apologize. I should have mentioned that I'm ran your program on cmd prompt on Windows (so I don't have vim).
This is what I get when I type `$profile` on my prompt. 
```
→ C:\Users\arpit\Desktop› $profile
'$profile' is not recognized as an internal or external command,
operable program or batch file.
``` 
I ran ``` set ``` to see the list of variables. While I did not find any variable named **profile**, I did see the variable
```
prompt=$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m
```
I think I set that manually following instructions from the readMe.
Later when I tried uninstalling, I might have removed the `profile` variable, I guess? 

What can I do now?

**Comment by gawronix** [comment]
run this in PS

**Comment by arpitkaushal** [comment]
@gawronix  I never installed it in Power Shell. Only did that to the command prompt. 
Anyway, the path returned by powershell was - 
``` C:\Users\arpit\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 ```
But when I run, 
``` notepad C:\Users\arpit\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 ```
Notepad says, the file doesn't exist, do you want to create a new file?
I went to the said path myself, to find an empty folder. Again, (maybe) because I never ran the "color program" on PowerShell. Only did it for cmd prompt.

**Comment by gawronix** [comment]
Ok, so you have to remove promt enviroment.
try this:
https://www.digitalcitizen.life/how-edit-or-delete-environment-variables-windows-7-windows-8

**Comment by arpitkaushal** [comment]
Okay, so I just had to see my environment variables in the Windows Advanced System settings, and delete the variable 
```prompt=$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m``` 
from before. 
Restarted the cmd prompt, and it's back to it's default state. Thanks for being helpful and patient! 
😄
