### ISSUE TITLE
Not show color

### ISSUE THREAD

**Issue by ThalysSilva** [dracula/powershell#33]
after installing and following the steps, everything works normally, but when you restart the console, it turns white again, with only the background with the theme color

**Comment by Re-fresh** [comment]
I'm facing the same problem

**Comment by waf** [comment]
Hi @ThalysSilva, would you be able to post a screenshot, and the output of this powershell command: `get-content $profile` 

Thanks!

**Comment by waf** [comment]
Closing out some older issues. Feel free to re-open if it's still affecting you.
