### ISSUE TITLE
Could not find or load "Dracula.ini"

### ISSUE THREAD

**Issue by welcometochristown** [dracula/powershell#37]
When I run `.\ColorTool.exe -b Dracula.ini` in powershell console I get the error saying it can't find or load Dracula.ini

![image](https://user-images.githubusercontent.com/17158437/87080955-8d99bd80-c1f6-11ea-84c0-184e543eb798.png)

Am I doing something wrong? I don't see a Dracula.ini file in the ColorTools folder. Is this a file that gets created?

**Comment by paulchiu** [comment]
The instructions appear to be out of date. The following works for me:

1. Download and extract https://github.com/dracula/powershell/raw/master/dist/ColorTool.zip
1. Run `install.cmd`

**Comment by williamisnotdefined** [comment]
I do this and has no effect :( 

> The instructions appear to be out of date. The following works for me:
> 
> 1. Download and extract https://github.com/dracula/powershell/raw/master/dist/ColorTool.zip
> 2. Run `install.cmd`

**Comment by waf** [comment]
Thanks @paulchiu for helping out! There was an inconsistency between the website and instructions in the readme. That inconsistency has been fixed now.
