### ISSUE TITLE
Colours are not what were shown in the front page

### ISSUE THREAD

**Issue by arjdroid** [dracula/powershell#38]
I ran the exact instructions to install the colour profile but it seems the colours are different from the one in the image above the instructions... I'd be happy to manually implement each of the colour values by hand if someone were to tell them to me!
![image](https://user-images.githubusercontent.com/57623600/88681270-05c91400-d10f-11ea-92dd-309402fbb3af.png)

**Comment by waf** [comment]
Hi @Arjdroid . Yes, that does not look good! Could you please confirm the following?

- In powershell, please run the following two commands and paste the output here:
  1. `(Get-Module PSReadLine).Version`
  1. `Get-PSReadLineOption`
- Does cmd.exe look correct?

Thanks!

**Comment by arjdroid** [comment]
For the first command, the output was -
![image](https://user-images.githubusercontent.com/57623600/88756837-444be680-d182-11ea-88ec-06ab0c8f3834.png)

The second output was - 
![image](https://user-images.githubusercontent.com/57623600/88756903-72312b00-d182-11ea-9dc4-fe235d7218e6.png)

Cmd.exe looks like this - 
![image](https://user-images.githubusercontent.com/57623600/88756966-95f47100-d182-11ea-8b2b-48be2e796ed3.png)
It didn't use to look like that before(I'm pretty sure) I executed install.cmd in powershell

**Comment by waf** [comment]
Ah, I think I've discovered what's happening. The website has out-of-date installation instructions -- it looks like the website was recently rewritten. I'll figure out how to get that updated.

In the meantime, could you please follow the "Colors Installation" and "PowerShell Prompt" instructions [on this page](https://github.com/dracula/powershell/blob/master/INSTALL.md)? You can follow the rest if you want, but it's not required.

**Comment by arjdroid** [comment]
Ah, I finally got it, I was only doing the Colors Installation part, not the PowerShell Prompt part... Thank you so much for your time, I'm sorry for wasting it! 👍 Its working fine now and looks great! 👍

**Comment by waf** [comment]
Glad you got it working! Thanks for opening the issue -- I can definitely see how the installation instructions need a bit of work to be more clear. I'll see if I can improve them.
