### ISSUE TITLE
git command could not be found

### ISSUE THREAD

**Issue by phillocoder** [dracula/powershell#39]
I get this warning in powershell after doing all the installation steps: "git command could not be found. Please create an alias or add it to your PATH."

**Comment by waf** [comment]
Hi @phillocoder. Do you have git installed? If not, you can [install it from this webpage](https://github.com/git-guides/install-git#install-git-on-windows).

**Comment by waf** [comment]
Closing out some older issues. Feel free to re-open if it's still affecting you.
