### ISSUE TITLE
Help to Configure

### ISSUE THREAD

**Issue by ErickRock** [dracula/powershell#40]
**Description of the issue**

Can someone make a video of teaching? I followed all the steps but I can't make it look like the sample image in readme.md.

**Screenshots**

*Me*:
![image](https://user-images.githubusercontent.com/15223763/90343220-b75bb680-dfe4-11ea-926b-40e80f75dbaf.png)

*As i want*:
![image](https://user-images.githubusercontent.com/15223763/90343225-cd697700-dfe4-11ea-8f9e-50700dd31afc.png)

**Version Information**

![image](https://user-images.githubusercontent.com/15223763/90343213-a90d9a80-dfe4-11ea-9ba4-606ef20ab4fa.png)

**Comment by waf** [comment]
Hi @ErickRock. It looks like it's almost right. Did you follow Step 4 in the installation instructions? Step 4 is:

> Include [this powershell configuration](https://github.com/dracula/powershell/blob/master/theme/dracula-prompt-configuration.ps1) in your PowerShell `$profile` file.

To explain more, find the file `C:\Users\{YourUserName}\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`. You can make a new file if it doesn't exist. Then copy/paste the powershell configuration linked above into that file.

**Comment by ErickRock** [comment]
Hi @waf!


I followed all the steps, but it is not the same. This is my $ profile

```powershell
Import-Module PSReadLine

# Dracula readline configuration. Requires version 2.0, if you have 1.2 convert to `Set-PSReadlineOption -TokenType`
Set-PSReadlineOption -Color @{
    "Command" = [ConsoleColor]::Green
    "Parameter" = [ConsoleColor]::Gray
    "Operator" = [ConsoleColor]::Magenta
    "Variable" = [ConsoleColor]::White
    "String" = [ConsoleColor]::Yellow
    "Number" = [ConsoleColor]::Blue
    "Type" = [ConsoleColor]::Cyan
    "Comment" = [ConsoleColor]::DarkCyan
}
# Dracula Prompt Configuration
Import-Module posh-git
$GitPromptSettings.DefaultPromptPrefix.Text = "$([char]0x2192) " # arrow unicode symbol
$GitPromptSettings.DefaultPromptPrefix.ForegroundColor = [ConsoleColor]::Green
$GitPromptSettings.DefaultPromptPath.ForegroundColor =[ConsoleColor]::Cyan
$GitPromptSettings.DefaultPromptSuffix.Text = "$([char]0x203A) " # chevron unicode symbol
$GitPromptSettings.DefaultPromptSuffix.ForegroundColor = [ConsoleColor]::Magenta
# Dracula Git Status Configuration
$GitPromptSettings.BeforeStatus.ForegroundColor = [ConsoleColor]::Blue
$GitPromptSettings.BranchColor.ForegroundColor = [ConsoleColor]::Blue
$GitPromptSettings.AfterStatus.ForegroundColor = [ConsoleColor]::Blue 

```

*PATH and Name*

![image](https://user-images.githubusercontent.com/15223763/90396108-0698fa00-e06c-11ea-836e-9d7d755a7f0c.png)

**Comment by waf** [comment]
Hi @ErickRock, looks like the filename is misspelled -- it's missing the <kbd>r</kbd> in PowerShell. 

It's a long filename, probably best if you copy/paste the full name: `Microsoft.PowerShell_profile.ps1`

**Comment by ErickRock** [comment]
Hi @waf ooo Thanks

I can't believe I missed something so simple, I feel ashamed ...

I changed the name, and then ran the command 

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
```
![image](https://user-images.githubusercontent.com/15223763/90399287-1961fd80-e071-11ea-8b9a-5f4125fd056a.png)


It worked!

Do you know how I do the following configuration for cmd?
<details><summary><strong>CMD.exe Prompt</strong></summary>
<p>

Set the environment variable `prompt` to `$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m`

</p>
</details>

**Comment by waf** [comment]
@ErickRock great! looks good. For cmd, you can set it in the Environment Variables:

1. In the Windows start menu, search for the word "environment". Choose "Edit Environment variables for your account"
![image](https://user-images.githubusercontent.com/97195/90409888-edc42f00-e0d3-11ea-83f1-6f55c0b8e4bb.png)
1. In the window that opens, click "New":
![image](https://user-images.githubusercontent.com/97195/90410083-2532db80-e0d4-11ea-9fb7-562db7346ec5.png)
1. Set the variable name to "prompt" and the variable value to `$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m`
![image](https://user-images.githubusercontent.com/97195/90410270-590e0100-e0d4-11ea-990c-7561e3462198.png)
1. Click OK to add the variable, then OK again (on the window from step 2) to save your changes.

**Comment by ErickRock** [comment]
Thank you very much for your help, thank you very much! It's all right now.

![image](https://user-images.githubusercontent.com/15223763/90416772-47533c00-e089-11ea-94c9-8186085fbc63.png)

**Comment by waf** [comment]
Great! Glad you got it working. 👍
