### ISSUE TITLE
Wrong symbols for CMD.exe on draculatheme.com

### ISSUE THREAD

**Issue by dimejo** [dracula/powershell#42]
## Description of the issue

When copying the prompt from [draculatheme.com/powershell](https://draculatheme.com/powershell), the symbols on the prompt are not displayed correctly. It looks like they somehow are converted when creating the website, because symbols on the Github site are correct.

## Screenshots

<img width="674" alt="dracula_powershell_prompt" src="https://user-images.githubusercontent.com/25005220/103522580-dfa45e80-4e7a-11eb-912b-5a464e5ac72f.png">
<img width="860" alt="dracula_powershell_website" src="https://user-images.githubusercontent.com/25005220/103522549-d4e9c980-4e7a-11eb-8a7d-c28497a2995d.png">
<img width="860" alt="dracula_powershell_github" src="https://user-images.githubusercontent.com/25005220/103522571-dc10d780-4e7a-11eb-8bea-00e047ce695f.png">

## Version Information

```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      -1
```

## Sitenote
[draculatheme.com/powershell](https://draculatheme.com/powershell) has some stray `</p>` in it as can be seen on the screenshot above.

**Comment by waf** [comment]
Ah, thanks for the report! Really appreciate you taking the time to point this out.

Yeah, something in the static site generator is messing up those symbols. I've switched it over to a plain text link; next time the static site gets regenerated it should fix this. I'll keep this issue open until that happens. Thanks!

**Comment by dimejo** [comment]
> Ah, thanks for the report! Really appreciate you taking the time to point this out.

Thank you for working on this. 😄
