### ISSUE TITLE
The property xyz cannot be found on this object.

### ISSUE THREAD

**Issue by JakubZ0** [dracula/powershell#43]
**Description of the issue**
Hello, I followed the instructions from https://draculatheme.com/powershell and after posting my Dracula configuration into $profile colors seem to look fine but the errors appear.

**Screenshots**
https://prnt.sc/whcvma

**Version Information**

v1.0 > (Get-Module PSReadline).Version; (Get-Module posh-git).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      2      0      -1
0      7      3      -1

also I'm adding my powershell configuration (had to copy it and change it to txt because Github doesn't support that kind of file formats.
[Microsoft.PowerShell_profile.txt](https://github.com/dracula/powershell/files/5774731/Microsoft.PowerShell_profile.txt)

**Comment by waf** [comment]
Hi @drawix. I think the posh-git module needs to be upgraded. Can you please try this part of Step 1 from the [INSTALL.md](https://github.com/dracula/powershell/blob/master/INSTALL.md)? Thanks!

> Install git integration (posh-git) with `Install-Module -Name posh-git -AllowPrerelease -Force`

**Comment by waf** [comment]
Closing this due to age. Feel free to reopen.
