### ISSUE TITLE
❯ not appearing showing 

### ISSUE THREAD

**Issue by RohitM-IN** [dracula/powershell#47]
**Description of the issue**

as you can see in the screen shot the ❯ icon is not appearing 

**Screenshots**
![image](https://user-images.githubusercontent.com/28777412/104577710-ce7bfe80-567f-11eb-8add-a719561f462a.png)

> If applicable, please provide a screenshot of the issue

**Version Information**
![image](https://user-images.githubusercontent.com/28777412/104577834-f4a19e80-567f-11eb-9fed-73ad39e724a3.png)

> Please provide the output of this PowerShell command: `(Get-Module PSReadline).Version; (Get-Module posh-git).Version`

**Comment by waf** [comment]
Hi @RootAndroid58, thanks for reporting this. In your screenshot, it looks like you're using Oh My Posh or some other prompt. Is that correct?

I think you'll need to select either Oh My Posh, or this prompt. They both want to control the prompt, so I'm not sure how they'd interact.

You might also try setting your terminal to render unicode; that's usually the issue when you see [?] characters.

**Comment by waf** [comment]
Closing this due to age. Feel free to reopen.
