### ISSUE TITLE
Theme takes twice (and then some) to load on PowerShell Core 7 than it takes on Windows PowerShell 5

### ISSUE THREAD

**Issue by peterlobster** [dracula/powershell#49]
**Description of the issue**

When loading the Dracula Theme in PowerShell 5, it usually takes about ~500ms. When loading the Dracula Them in PowerShell 7, it usually takes about ~1200ms.

**Screenshots**
`PowerShell 5`

![image](https://user-images.githubusercontent.com/38382145/119521373-98a40080-bd6a-11eb-852a-f174f8155847.png)

`PowerShell 7`

![image](https://user-images.githubusercontent.com/38382145/119521484-b5403880-bd6a-11eb-903b-4ef67ebff11b.png)

**Version Information**

> Please provide the output of this PowerShell command: `(Get-Module PSReadline).Version; (Get-Module posh-git).Version`

`PowerShell 5`
```shell
› (Get-Module PSReadline).Version; (Get-Module posh-git).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      -1
1      0      0      -1
```

`PowerShell 7`

```shell
› (Get-Module PSReadline).Version; (Get-Module posh-git).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      1      0      -1
1      0      0      -1
```

**Comment by waf** [comment]
My apologies for not responding sooner. If you disable the theme, do you see more similar performance? I suspect you'll still see a discrepancy. It'd also be helpful if you could share your PowerShell `$profile` file for both PowerShell 5 and PowerShell 7.

You may also want to follow this issue in the main PowerShell Core repository: https://github.com/PowerShell/PowerShell/issues/14268

**Comment by waf** [comment]
Anecdotally, with `PowerShell 7.2.0-preview.8`, it loads < 500ms, whereas PowerShell 5 took ~1200ms on the same computer. These are unscientific timings, though; they control for cold/warm startup times, but not much else.

**Comment by waf** [comment]
Closing stale issues, feel free to reopen if needed
