### ISSUE TITLE
Import-Module: The specified module 'posh-git' was not loaded.

### ISSUE THREAD

**Issue by DragonLover64** [dracula/powershell#50]
I don't know why this happens; this is my first time trying anything similar to this.
![dracula-issue](https://user-images.githubusercontent.com/67053195/127746267-fc4c623c-044d-4ce6-b6bd-1670d60c8b27.png)

**Comment by waf** [comment]
Hi. Could you please post the output of `(Get-Module PSReadline).Version; (Get-Module posh-git).Version`

Thanks!

**Comment by DragonLover64** [comment]
![ffbagjboodhipaca](https://user-images.githubusercontent.com/67053195/128373878-6875b7e5-535e-4a1d-bb95-a3bb19c0523b.png)
Hi. I am sorry for replying so late. An email was sent to me from this thread that said that I could reply to it directly or reply from the website but it seems that it didn't work properly.

**Comment by waf** [comment]
Can you please try installing posh-git from [these instructions](https://github.com/dracula/powershell/blob/master/INSTALL.md)? It's part of the "Powershell colors" section, in the first step. If you get an error, please let me know and I'll make these instructions more clear. Thanks!

**Comment by DragonLover64** [comment]
If I use `Install-Module -Name posh-git -AllowPrerelease -Force` without `-AllowPrerelease` it works! Thank you for your help.
