### ISSUE TITLE
Colors Errors

### ISSUE THREAD

**Issue by andrevandal** [dracula/powershell#8]
When I apply this theme, it looks like this:

![screenshot_1](https://user-images.githubusercontent.com/1340508/52630549-ab4ce100-2ea3-11e9-9e7b-ad5b8beea16b.png)

my $PROFILE
```
# Ensure that Get-ChildItemColor is loaded
Import-Module Get-ChildItemColor

# Set l and ls alias to use the new Get-ChildItemColor cmdlets
Set-Alias l Get-ChildItemColor -Option AllScope
Set-Alias ls Get-ChildItemColorFormatWide -Option AllScope

# Helper function to show Unicode characters
function U
{
    param
    (
        [int] $Code
    )
 
    if ((0 -le $Code) -and ($Code -le 0xFFFF))
    {
        return [char] $Code
    }
 
    if ((0x10000 -le $Code) -and ($Code -le 0x10FFFF))
    {
        return [char]::ConvertFromUtf32($Code)
    }
 
    throw "Invalid character code $Code"
}

# Ensure posh-git is loaded
Import-Module -Name posh-git

# Dracula readline configuration. Requires version 2.0, if you have 1.2 convert to `Set-PSReadlineOption -TokenType`
Set-PSReadlineOption -Color @{
    "Command" = [ConsoleColor]::Green
    "Parameter" = [ConsoleColor]::Gray
    "Operator" = [ConsoleColor]::Magenta
    "Variable" = [ConsoleColor]::White
    "String" = [ConsoleColor]::Yellow
    "Number" = [ConsoleColor]::Blue
    "Type" = [ConsoleColor]::Cyan
    "Comment" = [ConsoleColor]::DarkCyan
}
# Dracula Prompt Configuration
Import-Module posh-git
$GitPromptSettings.DefaultPromptPrefix.Text = "$([char]0x2192) " # arrow unicode symbol
$GitPromptSettings.DefaultPromptPrefix.ForegroundColor = [ConsoleColor]::Green
$GitPromptSettings.DefaultPromptPath.ForegroundColor =[ConsoleColor]::Cyan
$GitPromptSettings.DefaultPromptSuffix.Text = "$([char]0x203A) " # chevron unicode symbol
$GitPromptSettings.DefaultPromptSuffix.ForegroundColor = [ConsoleColor]::Magenta
# Dracula Git Status Configuration
$GitPromptSettings.BeforeStatus.ForegroundColor = [ConsoleColor]::Blue
$GitPromptSettings.BranchColor.ForegroundColor = [ConsoleColor]::Blue
$GitPromptSettings.AfterStatus.ForegroundColor = [ConsoleColor]::Blue

# Ensure oh-my-posh is loaded
Import-Module -Name oh-my-posh

# Set the default prompt theme
Set-Theme agnoster
```

**Comment by waf** [comment]
Thanks for the bug report, looks like it may be related to https://github.com/Microsoft/console/issues/23 , and I've verified that the behavior exists even on the most recent version of that tool.

A quick fix is to right-click on the titlebar of the powershell window and choose "Properties" &rarr; "Colors", and change "Screen Text" to the darker white color (8th from the left) and "Screen Background" to the black color (1st on the left). That should fix all future powershell windows.

I'll have to do more research to see if we can script this automatically.

**Comment by waf** [comment]
@derevandal I think I've come up with a better fix, by switching to an alternative file format in PR #9. 

Could you please try to apply [the zip file in that PR](https://github.com/dracula/powershell/blob/3e3a4ce3ae8e2907e4b36cc79750c559858f8f32/dist/ColorTool.zip)? If it works for you, I'll merge the PR and close out this issue.

**Comment by andrevandal** [comment]
It works here! Thanks!
Btw, i've got this error:
![image](https://user-images.githubusercontent.com/1340508/53295598-8e86a680-37dd-11e9-997d-c64bb1a62f77.png)
****

**Comment by waf** [comment]
Thanks for verifying it! I also get that error, but I think it's harmless. [Based on the source code](https://github.com/Microsoft/console/blob/bb795f52583e7e5f3bc8ac698464c600d3a9df95/tools/ColorTool/ColorTool/Program.cs#L566-L573), ColorTool (from Microsoft) is trying to parse it as an INI, failing, then moving on to the iterm parser which succeeds.

**Comment by oliemansm** [comment]
Had this same issue today. Perhaps the color tool link in the readme has not been updated?
